//GET all GeoTags
GET http://localhost:3000/api/geotags
Accept: application/json
###

//POST one GeoTag
POST http://localhost:3000/api/geotags
Content-Type: application/json

{
  "name":"Vallah",  
  "latitude":"49.013790",
  "longitude":"8.404435",
  "hashtag":"#Vallah"
}
###

//GET one GeoTag
GET http://localhost:3000/api/geotags/Castle
Accept: application/json
###

//GET test 
GET http://localhost:3000/api/geotags/Vallah

###
//PUT change one GeoTag with name test to Castle2. test is deleted and Castle 2 inserted at the beginning
PUT http://localhost:3000/api/geotags/test
Content-Type: application/json

{
  "name":"Castle2",
  "latitude":"49.013790",
  "longitude":"8.404435",
  "hashtag":"#sight"
}
###

//DELETE one GeoTag
DELETE http://localhost:3000/api/geotags/Castle2
###

//GET all GeoTags filtered with searchterm
GET http://localhost:3000/api/geotags?searchterm=Building
###

//GET all GeoTags filtered with location. All GeoTags inside the radius of this location
GET http://localhost:3000/api/geotags?latitude=49.00902&longitude=8.39772
###

//GET all GeoTags filtered with searchterm AND location
GET http://localhost:3000/api/geotags?searchterm=Building&latitude=49.00902&longitude=8.39772
###

